### ISSUE TITLE
One question about the persistent-view

### ISSUE THREAD

**Issue by hustnn** [donderom/monadzoo-persistent-view#1]
In your blog http://www.monadzoo.com/blog/2015/04/10/akka-persistent-views/.

You mentioned "If the actor is in the middle of updating the state it cannot be queried what makes the system less responsive.". But even if you have another model which is only used for query, you still need to poll the events from your original persistent actor and update the data in your view, so the case you mentioned in the original CURD case can still happen (query and updating can still happen at the same time).

I am confused about this.

**Comment by donderom** [comment]
Hi!
That's a good question!
You're right about querying and updating happening at the same time. The key difference is that the events in the views have been polled for some time and it has it's own independent state which allows it to serve the query requests even if persistent actor is in the middle of processing. Think about it as eventual consistency. When persistent actor is done with the new message it will be available in the views eventually but they are always ready to serve what they have already. To make it more intuitive the view keeps its own state. If it wouldn't then yes, there wouldn't be any much difference.
Hope it helps!

**Comment by donderom** [comment]
@hustnn Does it help?
